format="""
$hostname\
$directory\
$git_branch\
$character\
"""

add_newline = false

[character]
success_symbol = " [λ](yellow)"
error_symbol = " [λ](red)"
vicmd_symbol = " [λ](green)"

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 1
truncation_length = 1
style = "green"
format = "[$path](green)"

[hostname]
ssh_only = true
format = "[$hostname](red) "

[git_branch]
symbol = ""
format = "( [$symbol$branch](blue))"
