add_newline = false

format="""
$cmd_duration\
$env_var\
$aws\
"""

[aws]
format="([$symbol$profile](yellow) )"

[cmd_duration]
format = "([$duration](red) )"

[env_var]
variable = "current_docker"
format = "([$env_value](blue) )"
