add_newline = false
prompt_order=["hostname", "directory", "git_branch", "character"]

[character]      # The name of the module we are configuring is "character"
symbol = "λ"     # The "symbol" segment is being set to "➜"
style_success = "yellow"
style_failue = "red"

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 1
prefix = ""
truncation_length = 1
style = "green"

[hostname]
ssh_only = false
style = "red"

[git_branch]
symbol = ""
style = "blue"
