version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker
        #      - restore_cache:
        #          keys:
        #            - v1-{{ .Branch }}
        #          paths:
        #            - /caches/app.tar
        #      - run:
        #          name: Load Docker image layer cache
        #          command: |
        #            set +o pipefail
        #            docker load -i /caches/app.tar | true
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from=app -t llwwns/dev .
        #      - run:
        #          name: Save Docker image layer cache
        #          command: |
        #            mkdir -p /caches
        #            docker save -o /caches/app.tar llwwns/dev
        #      - save_cache:
        #          key: v1-{{ .Branch }}-{{ epoch }}
        #          paths:
        #            - /caches/app.tar
      - deploy:
          name: Push Docker image
          command: |
            docker login -u llwwns -p $DOCKER_PASS
            docker push llwwns/dev
