local plug = vim.fn["plug#"]
vim.fn["plug#begin"](vim.fn.stdpath('data') .. '/plugged')
plug('ryanoasis/vim-devicons' )
plug('Yggdroot/indentLine')
plug('tpope/vim-fugitive')
plug('mg979/vim-visual-multi')
plug('easymotion/vim-easymotion')
plug('haya14busa/vim-easyoperator-line')
if os.getenv("TMUXLINE") == '1' then
  plug('edkolev/tmuxline.vim')
end

plug('tpope/vim-unimpaired')
plug('godlygeek/tabular', { on = { 'Tabularize' }})
-- plug('mbbill/undotree', { on = { 'UndotreeShow' }})
plug('maksimr/vim-jsbeautify')
-- plug('einars/js-beautify')
plug('tpope/vim-abolish')
plug('tpope/vim-surround')
plug('wellle/targets.vim')
plug('mattn/emmet-vim')
plug('FooSoft/vim-argwrap', { on = {'ArgWrap'}})
plug('leafgarland/typescript-vim')
plug('ianks/vim-tsx')
plug('junegunn/vim-easy-align')
plug('w0rp/ale')
plug('sheerun/vim-polyglot')
plug('vim-airline/vim-airline')
plug('AndrewRadev/deleft.vim')
plug('neovim/nvim-lspconfig')
plug('haorenW1025/completion-nvim')
plug('scrooloose/nerdtree', { on = { 'NERDTreeToggle', 'NERDTreeFind' }})
plug('vim-scripts/BufOnly.vim', {on = {'BOnly'}})
plug('dbeniamine/todo.txt-vim')
plug('houtsnip/vim-emacscommandline')
plug('RRethy/vim-illuminate')
plug('junegunn/gv.vim', { on = { 'GV' }})
plug('lambdalisue/suda.vim')
plug('skywind3000/asyncrun.vim', { on = {'AsyncRun'} })
plug('tyru/eskk.vim')
plug('powerman/vim-plugin-AnsiEsc', { on = {'AnsiEsc'} })
-- plug('rhysd/reply.vim')
plug('tpope/vim-endwise')
plug('tomtom/tcomment_vim')
plug('bronson/vim-trailing-whitespace')
plug('machakann/vim-swap')
plug('mechatroner/rainbow_csv')
-- plug('tyrannicaltoucan/vim-quantum')
plug('google/vim-searchindex')
-- plug('junegunn/fzf', { dir = '~/fzf', ['do'] = './install --all' })
plug('junegunn/fzf.vim')
-- plug('whatyouhide/vim-gotham')
plug('rhysd/try-colorscheme.vim', { on = {'TryColorscheme'}})
plug('airblade/vim-gitgutter')
plug('tpope/vim-dadbod', { on = { 'DBUI' }})
plug('kristijanhusak/vim-dadbod-ui', { on = {'DBUI'}})
plug('norcalli/nvim-colorizer.lua')
plug('sainnhe/sonokai')
plug('kassio/neoterm', { on = {'Ttoggle'} })
plug('AndrewRadev/bufferize.vim')
plug('liuchengxu/vim-which-key', { on = {'WhichKey', 'WhichKey!'} })
plug('hrsh7th/vim-vsnip')
plug('hrsh7th/vim-vsnip-integ')
plug('luochen1990/rainbow')
plug('nvim-treesitter/nvim-treesitter')
plug('lukas-reineke/indent-blankline.nvim')
plug('bluz71/vim-moonfly-colors')
plug('Xuyuanp/scrollbar.nvim')
plug('ChristianChiarulli/nvcode-color-schemes.vim')
plug('simnalamburt/vim-mundo', { on = { 'MundoShow', 'MundoToggle' } })
-- plug('romgrk/barbar.nvim')
-- plug('kyazdani42/nvim-web-devicons')

vim.fn["plug#end"]()
